### ISSUE TITLE
Chat consistency

### ISSUE THREAD

**Issue by ryanleung** [ryanleung/connect_chrome#10]
Chat should follow URL at all time, currently only on tab change but need for window change, switching URL within tab, making new tab etc

**Comment by stumichael9109** [comment]
Left to do (3/16/15):

updateTab - opened chat needs to follow tab when updated. Implement this in
chrome.tabs.onUpdatedListner(...)

window change - need to implement chat box to follow tab on window change. Implement in:

chrome.windows.onFocusChanged(...)

**Comment by stumichael9109** [comment]
3/18/2015

done with updateTab to make chat follow the tab's updated urls.

Need to work on onRemoved to properly unset some chat attributes.

**Comment by stumichael9109** [comment]
Seems mostly done as well. Finished onFocusChanged.

Reopen with specific bugs.
